### ISSUE TITLE
Add/Generate API doc for REST API

### ISSUE THREAD

**Issue by gggodhwani** [DataKind-BLR/ichangemycity#7]
This will enhance usability.

**Comment by samarthbhargav** [comment]
@gggodhwani for this, I'm using Insomnia http://insomnia.rest/ , which has an export command. Either that or swagger http://swagger.io/ 
Which would you prefer? It's easier to build using insomnia, but swagger is more self contained and open.

**Comment by samarthbhargav** [comment]
This looks good: http://editor.swagger.io/

**Comment by samarthbhargav** [comment]
Updated docs. Closing
